### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by jschoch** [dtube/ipfs-uploader#5]
Wondering how this works, not a c# programmer so reading the source may not tell me what I need to know to set this up.  Are you open to starting a FAQ?

Here are some questions i have:

what is this, list functions.

what platforms are supported

how do you setup and configure it

**Comment by superkoala38** [comment]
Hello.
Documentation is on our todo list. Here a first explanation : https://busy.org/@superkoala/dtube-uploader-born-to-be-alive

**Comment by skzap** [comment]
This is a dotnet project, for development its recommended to have visual studio / code. Otherwise if it's just for production you just need the dotnet sdk.

It works like any dotnet project, you can `dotnet run`, `dotnet publish` to get it started. When it's up, it will listen on localhost:5000 for upcoming calls (/uploadVideo, /uploadImage, /getStatus, /getProgressByXXX, etc)

Yeah we need to write a full doc :+1:

**Comment by cryptopixelz** [comment]
Hi @superkoala38  anyway I can discuss with you about a project based on Dtube open source technology ? How can I contact you ? Je suis français aussi.

**Comment by superkoala38** [comment]
Hi! The owner is skzap, you must talk to him I think

**Comment by cryptopixelz** [comment]
Hi @skzap how can I reach you ? 😉
