### ISSUE TITLE
Offer more options for video formats (1080p, 720p, etc)

### ISSUE THREAD

**Issue by chrishobcroft** [dtube/ipfs-uploader#7]
I would like to be able to view Dtube videos in multiple different formats to suit my downstream bandwidth and screen resolution e.g. on smartphones.

Currently I can only watch at the resolution of the original "source" video, and something called 480 (I assume it is ~850x480 or 480x270?)

YouTube offers multiple different transcoded options such as:

1080p
720p
480p
360p
240p
144p

And also, resolution is getting bigger and bigger with 4K and UHD coming fast.

Take a look at Livepeer's decentralized livestreaming platform https://github.com/livepeer their primary function is transcoding video into multiple different bit rates and formats. The video doesn't need to be live-streamed although obviously it can be.

**Comment by skzap** [comment]
We are heavily working on this aspect. Our source code can work for any resolution and here are the currently accepted sizes: https://github.com/dtube/ipfs-uploader/blob/08d6dbd1a62749b1a0a109118a5d4bb117694228/Uploader.Core/Models/VideoSize.cs

The only reason we do not offer higher than 480p right now is because our current servers would not support the load. Code-wise, everything is ready ;)

**Comment by chrishobcroft** [comment]
Right, so, Livepeer is a decentralized transcoding service. You can send it a video and it will send you back transcoded videos, into whatever formats you ask for.

**Comment by chrishobcroft** [comment]
How come this issue is closed?

It's not implemented?

**Comment by chrishobcroft** [comment]
Maybe you want to trial Livepeer transcoding to do the transcoding work, instead of reinventing the wheel?

Get started here: http://livepeer.readthedocs.io
